-- Centro administrativo para usuarios con role = 'super_admin'.

create or replace function public.current_user_is_super_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select coalesce((
    select role = 'super_admin'
    from public.profiles
    where id = auth.uid()
    limit 1
  ), false)
$$;

grant execute on function public.current_user_is_super_admin() to authenticated;

create table if not exists public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  admin_user_id uuid not null references auth.users(id) on delete cascade,
  module text not null,
  action text not null,
  entity_table text,
  entity_id text,
  old_data jsonb,
  new_data jsonb,
  created_at timestamptz not null default now()
);

alter table public.admin_audit_logs enable row level security;

drop policy if exists "admin_audit_logs_super_admin_read" on public.admin_audit_logs;
create policy "admin_audit_logs_super_admin_read"
on public.admin_audit_logs for select
to authenticated
using (public.current_user_is_super_admin());

drop policy if exists "admin_audit_logs_super_admin_insert" on public.admin_audit_logs;
create policy "admin_audit_logs_super_admin_insert"
on public.admin_audit_logs for insert
to authenticated
with check (
  public.current_user_is_super_admin()
  and admin_user_id = auth.uid()
);

drop policy if exists "profiles_select_super_admin" on public.profiles;
create policy "profiles_select_super_admin"
on public.profiles for select
to authenticated
using (public.current_user_is_super_admin());

create or replace function public.admin_update_user_permissions(
  target_user_id uuid,
  next_role text,
  next_can_manage_appointments boolean
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  previous_profile jsonb;
  updated_profile jsonb;
begin
  if not public.current_user_is_super_admin() then
    raise exception 'Forbidden';
  end if;

  if next_role not in ('user', 'lider', 'super_admin') then
    raise exception 'Invalid role';
  end if;

  select to_jsonb(p) into previous_profile
  from public.profiles p
  where p.id = target_user_id;

  update public.profiles
  set
    role = next_role,
    can_manage_appointments = next_can_manage_appointments
  where id = target_user_id;

  select to_jsonb(p) into updated_profile
  from public.profiles p
  where p.id = target_user_id;

  insert into public.admin_audit_logs (
    admin_user_id, module, action, entity_table, entity_id, old_data, new_data
  )
  values (
    auth.uid(), 'users', 'update_permissions', 'profiles', target_user_id::text,
    previous_profile, updated_profile
  );
end;
$$;

grant execute on function public.admin_update_user_permissions(uuid, text, boolean) to authenticated;

-- Policies administrativas para contenido parametrizable.
do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'home_header',
    'home_banners',
    'daily_words',
    'home_stats',
    'home_sections',
    'home_quick_links',
    'events',
    'church_info',
    'church_locations_header',
    'church_locations',
    'leadership_schedule_header',
    'leadership_schedule_items',
    'weekly_songs_header',
    'weekly_songs',
    'home_featured_song',
    'daily_devotionals',
    'notification_master'
  ]
  loop
    if to_regclass(format('public.%I', table_name)) is not null then
      execute format('drop policy if exists %I on public.%I', table_name || '_admin_all', table_name);
      execute format(
        'create policy %I on public.%I for all to authenticated using (public.current_user_is_super_admin()) with check (public.current_user_is_super_admin())',
        table_name || '_admin_all',
        table_name
      );
    end if;
  end loop;
end
$$;
