create table if not exists public.bible_screen_content (
  id bigint generated by default as identity primary key,
  title text,
  subtitle text,
  empty_text text,
  is_active boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.bible_versions (
  id bigint generated by default as identity primary key,
  title text,
  description text,
  abbreviation text,
  viewer_url text not null,
  external_url text,
  sort_order int default 0,
  is_active boolean default true,
  created_at timestamptz default now()
);

alter table public.bible_screen_content enable row level security;
alter table public.bible_versions enable row level security;

drop policy if exists "bible_screen_content_read_active" on public.bible_screen_content;
create policy "bible_screen_content_read_active"
on public.bible_screen_content for select
to authenticated
using (is_active = true);

drop policy if exists "bible_versions_read_active" on public.bible_versions;
create policy "bible_versions_read_active"
on public.bible_versions for select
to authenticated
using (is_active = true);

update public.discipleship_modules
set route = '/discipulado/biblia'
where title = 'Biblia';

insert into public.bible_screen_content (title, subtitle, empty_text, is_active)
select
  'Biblia',
  'Selecciona una version para leer dentro de la app.',
  'No hay versiones disponibles.',
  true
where not exists (
  select 1 from public.bible_screen_content
);

insert into public.bible_versions (title, description, abbreviation, viewer_url, external_url, sort_order, is_active)
select 'Reina-Valera 1960', 'Version clasica en espanol.', 'RVR1960', 'https://www.bible.com/es/bible/149/GEN.1.RVR1960', 'https://www.bible.com/es/bible/149/GEN.1.RVR1960', 1, true
where not exists (select 1 from public.bible_versions where abbreviation = 'RVR1960');

insert into public.bible_versions (title, description, abbreviation, viewer_url, external_url, sort_order, is_active)
select 'Nueva Version Internacional', 'Lectura contemporanea en espanol.', 'NVI', 'https://www.bible.com/es/bible/128/GEN.1.NVI', 'https://www.bible.com/es/bible/128/GEN.1.NVI', 2, true
where not exists (select 1 from public.bible_versions where abbreviation = 'NVI');

insert into public.bible_versions (title, description, abbreviation, viewer_url, external_url, sort_order, is_active)
select 'Nueva Traduccion Viviente', 'Version clara y de lectura fluida.', 'NTV', 'https://www.bible.com/es/bible/127/GEN.1.NTV', 'https://www.bible.com/es/bible/127/GEN.1.NTV', 3, true
where not exists (select 1 from public.bible_versions where abbreviation = 'NTV');
