create or replace function public.current_user_is_super_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and role = 'super_admin'
  );
$$;

grant execute on function public.current_user_is_super_admin() to authenticated;

create table if not exists public.church_group_contacts_header (
  id bigint generated by default as identity primary key,
  menu_title text,
  screen_title text,
  subtitle text,
  is_active boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.church_group_contacts (
  id bigint generated by default as identity primary key,
  group_name text not null,
  contact_name text not null,
  email text,
  phone text,
  notes text,
  sort_order int default 0,
  is_active boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.church_group_contacts_header enable row level security;
alter table public.church_group_contacts enable row level security;

drop policy if exists "church_group_contacts_header_read_active" on public.church_group_contacts_header;
create policy "church_group_contacts_header_read_active"
on public.church_group_contacts_header for select
to authenticated
using (is_active = true);

drop policy if exists "church_group_contacts_read_active" on public.church_group_contacts;
create policy "church_group_contacts_read_active"
on public.church_group_contacts for select
to authenticated
using (is_active = true);

drop policy if exists "church_group_contacts_header_admin_all" on public.church_group_contacts_header;
create policy "church_group_contacts_header_admin_all"
on public.church_group_contacts_header for all
to authenticated
using (public.current_user_is_super_admin())
with check (public.current_user_is_super_admin());

drop policy if exists "church_group_contacts_admin_all" on public.church_group_contacts;
create policy "church_group_contacts_admin_all"
on public.church_group_contacts for all
to authenticated
using (public.current_user_is_super_admin())
with check (public.current_user_is_super_admin());

insert into public.church_group_contacts_header (menu_title, screen_title, subtitle, is_active)
select
  'Contactos de grupos',
  'Contactos de grupos',
  'Encuentra a la persona encargada de cada grupo o ministerio de la iglesia.',
  true
where not exists (select 1 from public.church_group_contacts_header);

insert into public.church_group_contacts (group_name, contact_name, email, phone, notes, sort_order, is_active)
select *
from (
  values
    ('Pastor', 'Julio Cely', 'pastorjuliocely@gmail.com', null, null, 1, true),
    ('Alabanza', 'Jackson Prieto', 'jackprietovargas@gmail.com', null, null, 2, true),
    ('Hombres', 'Anderson Cardenas', 'andeca20@gmail.com', null, null, 3, true),
    ('Staff', 'Diana Marin', 'dianamarin@gmail.com', null, null, 4, true),
    ('Intercesion', 'Luz Stella Gonzalez', 'luzstellagonzalez2005@gmail.com', null, null, 5, true),
    ('Evangelismo', 'Andrea Moreno', 'andrea.moreno07@hotmail.es', null, null, 6, true),
    ('Pastora y Mujeres', 'Maru Cely', 'marucely@live.com', null, null, 7, true)
) as seed(group_name, contact_name, email, phone, notes, sort_order, is_active)
where not exists (select 1 from public.church_group_contacts);
