create table if not exists public.church_locations_header (
  id bigint generated by default as identity primary key,
  menu_title text,
  screen_title text,
  subtitle text,
  is_active boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.church_locations (
  id bigint generated by default as identity primary key,
  name text,
  city text,
  address_line_1 text,
  address_line_2 text,
  service_times text,
  maps_url text,
  sort_order int default 0,
  is_active boolean default true,
  created_at timestamptz default now()
);

alter table public.church_locations_header enable row level security;
alter table public.church_locations enable row level security;

drop policy if exists "church_locations_header_read_active" on public.church_locations_header;
create policy "church_locations_header_read_active"
on public.church_locations_header for select
to authenticated
using (is_active = true);

drop policy if exists "church_locations_read_active" on public.church_locations;
create policy "church_locations_read_active"
on public.church_locations for select
to authenticated
using (is_active = true);

insert into public.church_locations_header (menu_title, screen_title, subtitle, is_active)
select 'Sedes', 'Nuestras sedes', 'Encuentra horarios y ubicacion de cada sede.', true
where not exists (select 1 from public.church_locations_header);

insert into public.church_locations (name, city, address_line_1, address_line_2, service_times, maps_url, sort_order, is_active)
select *
from (
  values
    (
      'Sede Frontino',
      'Antioquia, Colombia',
      'Templo Calle 31 26 c 76',
      'Barrio Juan 23',
      'Miercoles 4:00 pm' || chr(10) || 'Domingos 11:00 am',
      null,
      1,
      true
    ),
    (
      'Sede Medellin',
      'Sala DOS',
      'Centro Comercial Punto Clave',
      null,
      'Sabados 7:30 pm',
      null,
      2,
      true
    ),
    (
      'Sede Rionegro',
      'Torre Empresarial Savanna Plaza',
      'Diagonal al Exito Rionegro',
      'Auditorio 4to piso',
      'Domingos 10:00 am',
      null,
      3,
      true
    ),
    (
      'Sede New York',
      'Rye Brook',
      null,
      null,
      'Sabados 7:30 pm',
      null,
      4,
      true
    )
) as seed(name, city, address_line_1, address_line_2, service_times, maps_url, sort_order, is_active)
where not exists (select 1 from public.church_locations);
