create table if not exists public.church_info (
  id bigint generated by default as identity primary key,
  title text,
  subtitle text,
  who_title text,
  who_body text,
  vision_title text,
  vision_body text,
  mission_title text,
  mission_body text,
  is_active boolean default true,
  created_at timestamptz default now()
);

alter table public.church_info enable row level security;

drop policy if exists "church_info_read_active" on public.church_info;
create policy "church_info_read_active"
on public.church_info for select
to authenticated
using (is_active = true);

insert into public.church_info (
  title,
  subtitle,
  who_title,
  who_body,
  vision_title,
  vision_body,
  mission_title,
  mission_body,
  is_active
)
select
  'Vendimia',
  'Iglesia Cristiana Vendimia Medellin',
  'Quienes Somos',
  'La Iglesia Vendimia Medellin es una Iglesia Cristiana que se edifica en grupos pequenos, creemos y confiamos plenamente en Dios y en su Palabra, nuestras bases y fundamentos tienen como fin cumplir con el plan de Dios para llevar el regalo de la salvacion a todo lugar.

En la Iglesia Vendimia Medellin entendemos que cada grupo pequeno es mas que una reunion social y que cada una de nuestros grupos homogeneos, matrimonios, hombres, mujeres y jovenes, son la vida de la Iglesia y al hacerte parte de ellos desarrollaras relaciones fuertes y podras discutir la Palabra de Dios y saber como ponerla en practica activando tu fe.',
  'Vision',
  'Ser una iglesia con enfasis en el discipulado persona a persona, en la restauracion familia y la plantacion de nuevas Iglesias. Es por esto que nuestra vision es organica en su construccion, con relaciones familiares en su funcionamiento, biblica en su modelo, Cristo centrica en su operacion, y orientada hacia el Cuerpo en su unidad.',
  'Mision',
  'Llevar a las personas a un encuentro intimo y personal con Jesucristo y para esto la base fundamental es el discipulado persona a persona, el desarrollo integral del liderazgo y su ministerio ayudandoles a descubrir, desarrollar y usar sus dones espirituales. Es por esto que nuestra vision es organica en su construccion, con relaciones familiares en su funcionamiento, biblica en su modelo, Cristo centrica en su operacion, y orientada hacia el Cuerpo en su unidad.',
  true
where not exists (
  select 1 from public.church_info
);

update public.home_quick_links
set
  title = 'Información',
  route = '/(tabs)/more/info',
  icon_name = 'information-circle'
where title = 'Avisos' or route = '/(tabs)/more';
