create table if not exists public.daily_devotionals (
  id bigint generated by default as identity primary key,
  devotional_date date not null unique default ((now() at time zone 'America/Bogota')::date),
  title text not null,
  verse text not null,
  body text not null,
  is_active boolean not null default true,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.daily_devotionals enable row level security;

drop policy if exists "daily_devotionals_read_active" on public.daily_devotionals;
create policy "daily_devotionals_read_active"
on public.daily_devotionals for select
to authenticated
using (is_active = true);

drop policy if exists "daily_devotionals_insert_super_admin" on public.daily_devotionals;
create policy "daily_devotionals_insert_super_admin"
on public.daily_devotionals for insert
to authenticated
with check (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
    and profiles.role = 'super_admin'
  )
);

drop policy if exists "daily_devotionals_update_super_admin" on public.daily_devotionals;
create policy "daily_devotionals_update_super_admin"
on public.daily_devotionals for update
to authenticated
using (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
    and profiles.role = 'super_admin'
  )
)
with check (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
    and profiles.role = 'super_admin'
  )
);

insert into public.home_sections (section_key, title, action_text, sort_order, is_active)
select 'daily_devotional', 'Devocional diario', null, 1, true
where not exists (
  select 1
  from public.home_sections
  where section_key = 'daily_devotional'
);
