create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  email text not null,
  role text not null default 'user',
  avatar_url text,
  created_at timestamptz default now()
);

alter table public.profiles
add column if not exists avatar_url text;

revoke update on public.profiles from authenticated;
grant update (full_name, email, avatar_url) on public.profiles to authenticated;

create table if not exists public.profile_change_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  changed_by uuid references auth.users(id) on delete set null,
  field_name text not null,
  old_value text,
  new_value text,
  created_at timestamptz default now()
);

grant select, insert on public.profile_change_logs to authenticated;

create table if not exists public.user_push_tokens (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  expo_push_token text not null unique,
  platform text,
  is_active boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  title text not null,
  body text not null,
  target_role text,
  notification_type text not null default 'manual',
  scheduled_for timestamptz,
  sent_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz default now()
);

create table if not exists public.notification_deliveries (
  id bigint generated by default as identity primary key,
  notification_id bigint references public.notifications(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  expo_push_token text not null,
  status text not null default 'pending',
  response jsonb,
  created_at timestamptz default now()
);

create table if not exists public.home_header (
  id bigint generated by default as identity primary key,
  app_label text,
  title text,
  subtitle text,
  avatar_text text,
  is_active boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.home_banners (
  id bigint generated by default as identity primary key,
  title text,
  subtitle text,
  button_text text,
  button_route text,
  background_color text,
  accent_color text,
  badge_text text,
  image_url text,
  is_active boolean default true,
  sort_order int default 0,
  created_at timestamptz default now()
);

create table if not exists public.daily_words (
  id bigint generated by default as identity primary key,
  verse text,
  reference text,
  reflection text,
  accent_color text,
  is_active boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.home_stats (
  id bigint generated by default as identity primary key,
  label text,
  value text,
  sort_order int default 0,
  is_active boolean default true
);

create table if not exists public.home_sections (
  id bigint generated by default as identity primary key,
  section_key text,
  title text,
  action_text text,
  sort_order int default 0,
  is_active boolean default true
);

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  title text,
  description text,
  event_date date,
  event_time text,
  location text,
  background_color text,
  accent_color text,
  image_url text,
  show_on_home boolean default false,
  home_sort_order int default 0,
  is_active boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.home_quick_links (
  id bigint generated by default as identity primary key,
  title text,
  route text,
  icon_name text,
  background_color text,
  accent_color text,
  sort_order int default 0,
  is_active boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.church_info (
  id bigint generated by default as identity primary key,
  title text,
  subtitle text,
  who_title text,
  who_body text,
  vision_title text,
  vision_body text,
  mission_title text,
  mission_body text,
  is_active boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.devotionals (
  id bigint generated by default as identity primary key,
  title text,
  description text,
  icon text,
  is_active boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.prayer_highlights (
  id bigint generated by default as identity primary key,
  title text,
  description text,
  button_text text,
  is_active boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.prayer_screen_content (
  id bigint generated by default as identity primary key,
  title text,
  subtitle text,
  input_placeholder text,
  button_text text,
  empty_text text,
  like_text text,
  unlike_text text,
  is_active boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.prayer_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  body text not null,
  is_active boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.prayer_request_likes (
  id bigint generated by default as identity primary key,
  request_id bigint not null references public.prayer_requests(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz default now(),
  constraint prayer_request_likes_request_user_unique unique (request_id, user_id)
);

create table if not exists public.discipleship_header (
  id bigint generated by default as identity primary key,
  app_label text,
  title text,
  subtitle text,
  is_active boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.discipleship_modules (
  id bigint generated by default as identity primary key,
  title text,
  description text,
  icon_name text,
  route text,
  background_color text,
  accent_color text,
  sort_order int default 0,
  is_active boolean default true,
  created_at timestamptz default now()
);

insert into storage.buckets (id, name, public)
values ('discipleship-materials', 'discipleship-materials', false)
on conflict (id) do update set public = false;

insert into storage.buckets (id, name, public)
values ('profile-avatars', 'profile-avatars', true)
on conflict (id) do update set public = true;

create table if not exists public.discipleship_materials (
  id bigint generated by default as identity primary key,
  title text,
  description text,
  bucket_id text not null default 'discipleship-materials',
  storage_path text not null,
  allowed_role text not null default 'lider',
  sort_order int default 0,
  is_active boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.discipleship_notes_content (
  id bigint generated by default as identity primary key,
  title text,
  subtitle text,
  title_placeholder text,
  body_placeholder text,
  button_text text,
  empty_text text,
  is_active boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.discipleship_notes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text,
  body text not null,
  note_date date not null default current_date,
  created_at timestamptz default now()
);

create table if not exists public.bible_screen_content (
  id bigint generated by default as identity primary key,
  title text,
  subtitle text,
  empty_text text,
  is_active boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.bible_versions (
  id bigint generated by default as identity primary key,
  title text,
  description text,
  abbreviation text,
  viewer_url text not null,
  external_url text,
  sort_order int default 0,
  is_active boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.devotional_screen_content (
  id bigint generated by default as identity primary key,
  title text,
  subtitle text,
  search_placeholder text,
  reference_placeholder text,
  title_placeholder text,
  notes_title text,
  note_placeholder text,
  save_button_text text,
  empty_text text,
  is_active boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.devotional_passages (
  id bigint generated by default as identity primary key,
  title text,
  description text,
  passage_reference text,
  viewer_url text,
  external_url text,
  sort_order int default 0,
  is_active boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.devotional_notes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  passage_id bigint references public.devotional_passages(id) on delete cascade,
  passage_reference text,
  title text,
  body text not null,
  note_date date not null default current_date,
  created_at timestamptz default now()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, email)
  values (
    new.id,
    coalesce(nullif(new.raw_user_meta_data->>'full_name', ''), split_part(new.email, '@', 1)),
    new.email
  );
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.profile_change_logs enable row level security;
alter table public.user_push_tokens enable row level security;
alter table public.notifications enable row level security;
alter table public.notification_deliveries enable row level security;
alter table public.home_header enable row level security;
alter table public.home_banners enable row level security;
alter table public.daily_words enable row level security;
alter table public.home_stats enable row level security;
alter table public.home_sections enable row level security;
alter table public.home_quick_links enable row level security;
alter table public.church_info enable row level security;
alter table public.events enable row level security;
alter table public.devotionals enable row level security;
alter table public.prayer_highlights enable row level security;
alter table public.prayer_screen_content enable row level security;
alter table public.prayer_requests enable row level security;
alter table public.prayer_request_likes enable row level security;
alter table public.discipleship_header enable row level security;
alter table public.discipleship_modules enable row level security;
alter table public.discipleship_materials enable row level security;
alter table public.discipleship_notes_content enable row level security;
alter table public.discipleship_notes enable row level security;
alter table public.bible_screen_content enable row level security;
alter table public.bible_versions enable row level security;
alter table public.devotional_screen_content enable row level security;
alter table public.devotional_passages enable row level security;
alter table public.devotional_notes enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
on public.profiles for select
to authenticated
using (auth.uid() = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
on public.profiles for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "profile_change_logs_select_own" on public.profile_change_logs;
create policy "profile_change_logs_select_own"
on public.profile_change_logs for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "profile_change_logs_insert_own_password" on public.profile_change_logs;
create policy "profile_change_logs_insert_own_password"
on public.profile_change_logs for insert
to authenticated
with check (
  auth.uid() = user_id
  and auth.uid() = changed_by
  and field_name = 'password'
);

drop policy if exists "user_push_tokens_select_own" on public.user_push_tokens;
create policy "user_push_tokens_select_own"
on public.user_push_tokens for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "user_push_tokens_insert_own" on public.user_push_tokens;
create policy "user_push_tokens_insert_own"
on public.user_push_tokens for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "user_push_tokens_update_own" on public.user_push_tokens;
create policy "user_push_tokens_update_own"
on public.user_push_tokens for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "notifications_select_super_admin" on public.notifications;
create policy "notifications_select_super_admin"
on public.notifications for select
to authenticated
using (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
    and profiles.role = 'super_admin'
  )
);

drop policy if exists "notification_deliveries_select_super_admin" on public.notification_deliveries;
create policy "notification_deliveries_select_super_admin"
on public.notification_deliveries for select
to authenticated
using (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
    and profiles.role = 'super_admin'
  )
);

create or replace function public.log_profile_changes()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if old.full_name is distinct from new.full_name then
    insert into public.profile_change_logs (user_id, changed_by, field_name, old_value, new_value)
    values (new.id, auth.uid(), 'full_name', old.full_name, new.full_name);
  end if;

  if old.email is distinct from new.email then
    insert into public.profile_change_logs (user_id, changed_by, field_name, old_value, new_value)
    values (new.id, auth.uid(), 'email', old.email, new.email);
  end if;

  if old.avatar_url is distinct from new.avatar_url then
    insert into public.profile_change_logs (user_id, changed_by, field_name, old_value, new_value)
    values (new.id, auth.uid(), 'avatar_url', old.avatar_url, new.avatar_url);
  end if;

  return new;
end;
$$;

drop trigger if exists on_profile_updated_log_changes on public.profiles;

create trigger on_profile_updated_log_changes
after update of full_name, email, avatar_url on public.profiles
for each row execute function public.log_profile_changes();

drop policy if exists "profile_avatars_read" on storage.objects;
create policy "profile_avatars_read"
on storage.objects for select
to authenticated
using (bucket_id = 'profile-avatars');

drop policy if exists "profile_avatars_insert_own" on storage.objects;
create policy "profile_avatars_insert_own"
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'profile-avatars'
  and auth.uid()::text = (storage.foldername(name))[1]
);

drop policy if exists "profile_avatars_update_own" on storage.objects;
create policy "profile_avatars_update_own"
on storage.objects for update
to authenticated
using (
  bucket_id = 'profile-avatars'
  and auth.uid()::text = (storage.foldername(name))[1]
)
with check (
  bucket_id = 'profile-avatars'
  and auth.uid()::text = (storage.foldername(name))[1]
);

drop policy if exists "profile_avatars_delete_own" on storage.objects;
create policy "profile_avatars_delete_own"
on storage.objects for delete
to authenticated
using (
  bucket_id = 'profile-avatars'
  and auth.uid()::text = (storage.foldername(name))[1]
);

drop policy if exists "home_header_read_active" on public.home_header;
create policy "home_header_read_active"
on public.home_header for select
to authenticated
using (is_active = true);

drop policy if exists "home_banners_read_active" on public.home_banners;
create policy "home_banners_read_active"
on public.home_banners for select
to authenticated
using (is_active = true);

drop policy if exists "daily_words_read_active" on public.daily_words;
create policy "daily_words_read_active"
on public.daily_words for select
to authenticated
using (is_active = true);

drop policy if exists "home_stats_read_active" on public.home_stats;
create policy "home_stats_read_active"
on public.home_stats for select
to authenticated
using (is_active = true);

drop policy if exists "home_sections_read_active" on public.home_sections;
create policy "home_sections_read_active"
on public.home_sections for select
to authenticated
using (is_active = true);

drop policy if exists "home_quick_links_read_active" on public.home_quick_links;
create policy "home_quick_links_read_active"
on public.home_quick_links for select
to authenticated
using (is_active = true);

drop policy if exists "church_info_read_active" on public.church_info;
create policy "church_info_read_active"
on public.church_info for select
to authenticated
using (is_active = true);

drop policy if exists "events_read_active" on public.events;
create policy "events_read_active"
on public.events for select
to authenticated
using (is_active = true);

drop policy if exists "devotionals_read_active" on public.devotionals;
create policy "devotionals_read_active"
on public.devotionals for select
to authenticated
using (is_active = true);

drop policy if exists "prayer_highlights_read_active" on public.prayer_highlights;
create policy "prayer_highlights_read_active"
on public.prayer_highlights for select
to authenticated
using (is_active = true);

drop policy if exists "prayer_screen_content_read_active" on public.prayer_screen_content;
create policy "prayer_screen_content_read_active"
on public.prayer_screen_content for select
to authenticated
using (is_active = true);

drop policy if exists "prayer_requests_read_active" on public.prayer_requests;
create policy "prayer_requests_read_active"
on public.prayer_requests for select
to authenticated
using (is_active = true);

drop policy if exists "prayer_requests_insert_own" on public.prayer_requests;
create policy "prayer_requests_insert_own"
on public.prayer_requests for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "prayer_requests_update_own" on public.prayer_requests;
create policy "prayer_requests_update_own"
on public.prayer_requests for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "prayer_request_likes_read" on public.prayer_request_likes;
create policy "prayer_request_likes_read"
on public.prayer_request_likes for select
to authenticated
using (true);

drop policy if exists "prayer_request_likes_insert_own" on public.prayer_request_likes;
create policy "prayer_request_likes_insert_own"
on public.prayer_request_likes for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "prayer_request_likes_delete_own" on public.prayer_request_likes;
create policy "prayer_request_likes_delete_own"
on public.prayer_request_likes for delete
to authenticated
using (auth.uid() = user_id);

drop policy if exists "discipleship_header_read_active" on public.discipleship_header;
create policy "discipleship_header_read_active"
on public.discipleship_header for select
to authenticated
using (is_active = true);

drop policy if exists "discipleship_modules_read_active" on public.discipleship_modules;
create policy "discipleship_modules_read_active"
on public.discipleship_modules for select
to authenticated
using (is_active = true);

drop policy if exists "discipleship_materials_read_by_role" on public.discipleship_materials;
create policy "discipleship_materials_read_by_role"
on public.discipleship_materials for select
to authenticated
using (
  is_active = true
  and exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
    and profiles.role = discipleship_materials.allowed_role
  )
);

drop policy if exists "discipleship_material_files_read_by_lider" on storage.objects;
create policy "discipleship_material_files_read_by_lider"
on storage.objects for select
to authenticated
using (
  bucket_id = 'discipleship-materials'
  and exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
    and profiles.role = 'lider'
  )
);

drop policy if exists "discipleship_notes_content_read_active" on public.discipleship_notes_content;
create policy "discipleship_notes_content_read_active"
on public.discipleship_notes_content for select
to authenticated
using (is_active = true);

drop policy if exists "discipleship_notes_select_own" on public.discipleship_notes;
create policy "discipleship_notes_select_own"
on public.discipleship_notes for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "discipleship_notes_insert_own" on public.discipleship_notes;
create policy "discipleship_notes_insert_own"
on public.discipleship_notes for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "discipleship_notes_update_own" on public.discipleship_notes;
create policy "discipleship_notes_update_own"
on public.discipleship_notes for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "discipleship_notes_delete_own" on public.discipleship_notes;
create policy "discipleship_notes_delete_own"
on public.discipleship_notes for delete
to authenticated
using (auth.uid() = user_id);

drop policy if exists "bible_screen_content_read_active" on public.bible_screen_content;
create policy "bible_screen_content_read_active"
on public.bible_screen_content for select
to authenticated
using (is_active = true);

drop policy if exists "bible_versions_read_active" on public.bible_versions;
create policy "bible_versions_read_active"
on public.bible_versions for select
to authenticated
using (is_active = true);

drop policy if exists "devotional_screen_content_read_active" on public.devotional_screen_content;
create policy "devotional_screen_content_read_active"
on public.devotional_screen_content for select
to authenticated
using (is_active = true);

drop policy if exists "devotional_passages_read_active" on public.devotional_passages;
create policy "devotional_passages_read_active"
on public.devotional_passages for select
to authenticated
using (is_active = true);

drop policy if exists "devotional_notes_select_own" on public.devotional_notes;
create policy "devotional_notes_select_own"
on public.devotional_notes for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "devotional_notes_insert_own" on public.devotional_notes;
create policy "devotional_notes_insert_own"
on public.devotional_notes for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "devotional_notes_update_own" on public.devotional_notes;
create policy "devotional_notes_update_own"
on public.devotional_notes for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "devotional_notes_delete_own" on public.devotional_notes;
create policy "devotional_notes_delete_own"
on public.devotional_notes for delete
to authenticated
using (auth.uid() = user_id);

delete from public.devotional_passages
where passage_reference in ('Salmo 119:105', 'Juan 3:16', 'Juan 15');

delete from public.devotional_screen_content
where title = 'Devocionales';

delete from public.bible_versions
where abbreviation in ('RVR1960', 'NVI', 'NTV');

delete from public.bible_screen_content
where title = 'Biblia';

delete from public.discipleship_notes_content
where title = 'Notas personales';

delete from public.discipleship_materials
where storage_path = 'cartilla-discipulado-personal.pdf';

delete from public.discipleship_modules
where title in ('Devocionales', 'Notas', 'Material', 'Biblia', 'Estudios');

delete from public.discipleship_header
where app_label = 'Discipulado';

delete from public.prayer_screen_content
where title = 'Oración';

delete from public.prayer_highlights
where title = 'Comparte tu petición';

delete from public.devotionals
where title = 'Devocional semanal';

delete from public.events
where title in ('Reunión general', 'Noche de oración');

delete from public.church_info
where title = 'Vendimia';

delete from public.home_quick_links
where title in ('Discipulado', 'Oración', 'Eventos', 'Información');

delete from public.home_sections
where section_key in ('quick_links', 'upcoming_events', 'next_event', 'devotional', 'prayer');

delete from public.home_stats
where label in ('Grupos activos', 'Servidores', 'Eventos del mes');

delete from public.daily_words
where reference = 'Salmo 119:105';

delete from public.home_banners
where title = 'Campamento de Jovenes';

delete from public.home_header
where app_label = 'Vendimia';

insert into public.home_header (app_label, title, subtitle, avatar_text, is_active)
values ('Vendimia', 'Bienvenido a Vendimia', 'Conectados para crecer en Cristo', null, true);

insert into public.home_banners (title, subtitle, button_text, button_route, background_color, accent_color, badge_text, image_url, is_active, sort_order)
values
  ('Campamento de Jovenes', '5 Abril 2025', 'Ver detalles', '/(tabs)/events', '#9A4F08', '#F9820B', 'Febrero', 'https://images.unsplash.com/photo-1507692049790-de58290a4334?auto=format&fit=crop&w=1200&q=80', true, 1);

insert into public.daily_words (verse, reference, reflection, accent_color, is_active)
values ('Lámpara es a mis pies tu palabra, y lumbrera a mi camino.', 'Salmo 119:105', 'La Palabra de Dios guía cada paso con claridad y esperanza.', '#F9820B', true);

insert into public.home_stats (label, value, sort_order, is_active)
values
  ('Grupos activos', '12', 1, true),
  ('Servidores', '48', 2, true),
  ('Eventos del mes', '6', 3, true);

insert into public.home_sections (section_key, title, action_text, sort_order, is_active)
values
  ('quick_links', 'Accesos rapidos', null, 0, true),
  ('upcoming_events', 'Proximos eventos', null, 1, true),
  ('next_event', 'Próximo evento', 'Ver eventos', 2, true),
  ('devotional', 'Devocional destacado', 'Abrir', 2, true),
  ('prayer', 'Oración destacada', 'Orar ahora', 3, true);

insert into public.home_quick_links (title, route, icon_name, background_color, accent_color, sort_order, is_active)
values
  ('Discipulado', '/(tabs)/discipulado', 'book', '#1F1F1F', '#F9820B', 1, true),
  ('Oración', '/(tabs)/prayer', 'heart', '#1F1F1F', '#F9820B', 2, true),
  ('Eventos', '/(tabs)/events', 'calendar', '#1F1F1F', '#F9820B', 3, true),
  ('Información', '/(tabs)/more/info', 'information-circle', '#1F1F1F', '#F9820B', 4, true);

insert into public.church_info (
  title,
  subtitle,
  who_title,
  who_body,
  vision_title,
  vision_body,
  mission_title,
  mission_body,
  is_active
)
values (
  'Vendimia',
  'Iglesia Cristiana Vendimia Medellin',
  'Quienes Somos',
  'La Iglesia Vendimia Medellin es una Iglesia Cristiana que se edifica en grupos pequenos, creemos y confiamos plenamente en Dios y en su Palabra, nuestras bases y fundamentos tienen como fin cumplir con el plan de Dios para llevar el regalo de la salvacion a todo lugar.

En la Iglesia Vendimia Medellin entendemos que cada grupo pequeno es mas que una reunion social y que cada una de nuestros grupos homogeneos, matrimonios, hombres, mujeres y jovenes, son la vida de la Iglesia y al hacerte parte de ellos desarrollaras relaciones fuertes y podras discutir la Palabra de Dios y saber como ponerla en practica activando tu fe.',
  'Vision',
  'Ser una iglesia con enfasis en el discipulado persona a persona, en la restauracion familia y la plantacion de nuevas Iglesias. Es por esto que nuestra vision es organica en su construccion, con relaciones familiares en su funcionamiento, biblica en su modelo, Cristo centrica en su operacion, y orientada hacia el Cuerpo en su unidad.',
  'Mision',
  'Llevar a las personas a un encuentro intimo y personal con Jesucristo y para esto la base fundamental es el discipulado persona a persona, el desarrollo integral del liderazgo y su ministerio ayudandoles a descubrir, desarrollar y usar sus dones espirituales. Es por esto que nuestra vision es organica en su construccion, con relaciones familiares en su funcionamiento, biblica en su modelo, Cristo centrica en su operacion, y orientada hacia el Cuerpo en su unidad.',
  true
);

insert into public.events (title, description, event_date, event_time, location, background_color, accent_color, image_url, show_on_home, home_sort_order, is_active)
values
  ('Reunión general', 'Tiempo de adoración, enseñanza y comunidad.', current_date + interval '7 days', '10:00 AM', 'Auditorio principal', '#263B4A', '#F9820B', 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80', true, 2, true),
  ('Noche de oración', 'Un encuentro para interceder y agradecer juntos.', current_date + interval '3 days', '7:00 PM', 'Salón principal', '#3A1F2A', '#F9820B', 'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?auto=format&fit=crop&w=900&q=80', true, 1, true);

insert into public.devotionals (title, description, icon, is_active)
values ('Devocional semanal', 'Una lectura breve para fortalecer tu fe durante la semana.', 'book', true);

insert into public.prayer_highlights (title, description, button_text, is_active)
values ('Comparte tu petición', 'Permite que el equipo de oración acompañe tu proceso.', 'Enviar petición', true);

insert into public.prayer_screen_content (title, subtitle, input_placeholder, button_text, empty_text, like_text, unlike_text, is_active)
values ('Oración', 'Comparte tus motivos y acompaña en oración a la comunidad.', 'Escribe tu motivo de oración...', 'Publicar motivo', 'Aún no hay motivos de oración publicados.', 'Estoy orando', 'Orando', true);

insert into public.discipleship_header (app_label, title, subtitle, is_active)
values ('Discipulado', 'Crece con propósito', 'Recursos organizados para formación, estudio y seguimiento espiritual.', true);

insert into public.discipleship_modules (title, description, icon_name, route, background_color, accent_color, sort_order, is_active)
values
  ('Devocionales', 'Lecturas para fortalecer tu vida diaria con Dios.', 'book', '/discipulado/devocionales', '#1F1F1F', '#F9820B', 1, true),
  ('Notas', 'Apuntes y reflexiones personales de cada enseñanza.', 'create', '/discipulado/notas', '#1F1F1F', '#F9820B', 2, true),
  ('Material', 'Recursos de estudio para grupos y formación.', 'folder-open', '/discipulado/material', '#1F1F1F', '#F9820B', 3, true),
  ('Biblia', 'Acceso y guía para lectura bíblica.', 'reader', '/discipulado/biblia', '#1F1F1F', '#F9820B', 4, true),
  ('Estudios', 'Series y rutas de aprendizaje espiritual.', 'school', '/(tabs)/discipulado', '#1F1F1F', '#F9820B', 5, true);

insert into public.discipleship_materials (title, description, bucket_id, storage_path, allowed_role, sort_order, is_active)
values ('Cartilla de Discipulado Personal', 'Material de formacion para lideres.', 'discipleship-materials', 'cartilla-discipulado-personal.pdf', 'lider', 1, true);

insert into public.discipleship_notes_content (title, subtitle, title_placeholder, body_placeholder, button_text, empty_text, is_active)
values ('Notas personales', 'Guarda apuntes privados de tu proceso de discipulado.', 'Titulo opcional', 'Escribe tu nota...', 'Guardar nota', 'Aun no tienes notas guardadas.', true);

insert into public.bible_screen_content (title, subtitle, empty_text, is_active)
values ('Biblia', 'Selecciona una version para leer dentro de la app.', 'No hay versiones disponibles.', true);

insert into public.bible_versions (title, description, abbreviation, viewer_url, external_url, sort_order, is_active)
values
  ('Reina-Valera 1960', 'Version clasica en espanol.', 'RVR1960', 'https://www.bible.com/es/bible/149/GEN.1.RVR1960', 'https://www.bible.com/es/bible/149/GEN.1.RVR1960', 1, true),
  ('Nueva Version Internacional', 'Lectura contemporanea en espanol.', 'NVI', 'https://www.bible.com/es/bible/128/GEN.1.NVI', 'https://www.bible.com/es/bible/128/GEN.1.NVI', 2, true),
  ('Nueva Traduccion Viviente', 'Version clara y de lectura fluida.', 'NTV', 'https://www.bible.com/es/bible/127/GEN.1.NTV', 'https://www.bible.com/es/bible/127/GEN.1.NTV', 3, true);

insert into public.devotional_screen_content (title, subtitle, reference_placeholder, title_placeholder, note_placeholder, save_button_text, empty_text, is_active)
values ('Devocionales', 'Guarda notas personales segun el versiculo o capitulo que estas estudiando.', 'Versiculo o capitulo, por ejemplo Juan 15 o Salmo 119:105', 'Titulo opcional', 'Escribe tu nota...', 'Guardar nota', 'Aun no tienes notas devocionales guardadas.', true);

insert into public.devotional_passages (title, description, passage_reference, viewer_url, external_url, sort_order, is_active)
values
  ('La Palabra como guia', 'Devocional para meditar en la direccion de Dios.', 'Salmo 119:105', 'https://www.bible.com/es/bible/149/PSA.119.105.RVR1960', 'https://www.bible.com/es/bible/149/PSA.119.105.RVR1960', 1, true),
  ('Nuevo nacimiento', 'Devocional sobre la vida nueva en Cristo.', 'Juan 3:16', 'https://www.bible.com/es/bible/149/JHN.3.16.RVR1960', 'https://www.bible.com/es/bible/149/JHN.3.16.RVR1960', 2, true),
  ('Permanecer en Cristo', 'Devocional para revisar fruto, dependencia y comunion.', 'Juan 15', 'https://www.bible.com/es/bible/149/JHN.15.RVR1960', 'https://www.bible.com/es/bible/149/JHN.15.RVR1960', 3, true);
