create table if not exists public.devotional_screen_content (
  id bigint generated by default as identity primary key,
  title text,
  subtitle text,
  search_placeholder text,
  notes_title text,
  note_placeholder text,
  save_button_text text,
  empty_text text,
  is_active boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.devotional_passages (
  id bigint generated by default as identity primary key,
  title text,
  description text,
  passage_reference text,
  viewer_url text,
  external_url text,
  sort_order int default 0,
  is_active boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.devotional_notes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  passage_id bigint not null references public.devotional_passages(id) on delete cascade,
  body text not null,
  note_date date not null default ((now() at time zone 'America/Bogota')::date),
  is_active boolean not null default true,
  created_at timestamptz default now(),
  updated_at timestamptz not null default now()
);

alter table public.devotional_notes
add column if not exists is_active boolean not null default true;

alter table public.devotional_notes
add column if not exists updated_at timestamptz not null default now();

alter table public.devotional_screen_content enable row level security;
alter table public.devotional_passages enable row level security;
alter table public.devotional_notes enable row level security;

drop policy if exists "devotional_screen_content_read_active" on public.devotional_screen_content;
create policy "devotional_screen_content_read_active"
on public.devotional_screen_content for select
to authenticated
using (is_active = true);

drop policy if exists "devotional_passages_read_active" on public.devotional_passages;
create policy "devotional_passages_read_active"
on public.devotional_passages for select
to authenticated
using (is_active = true);

drop policy if exists "devotional_notes_select_own" on public.devotional_notes;
create policy "devotional_notes_select_own"
on public.devotional_notes for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "devotional_notes_insert_own" on public.devotional_notes;
create policy "devotional_notes_insert_own"
on public.devotional_notes for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "devotional_notes_update_own" on public.devotional_notes;
create policy "devotional_notes_update_own"
on public.devotional_notes for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "devotional_notes_delete_own" on public.devotional_notes;

update public.discipleship_modules
set route = '/discipulado/devocionales'
where title = 'Devocionales';

insert into public.devotional_screen_content (title, subtitle, search_placeholder, notes_title, note_placeholder, save_button_text, empty_text, is_active)
select
  'Devocionales',
  'Busca el pasaje del devocional y guarda tus notas personales.',
  'Buscar versiculo, capitulo o tema...',
  'Mis notas',
  'Escribe lo que Dios te muestra en este pasaje...',
  'Guardar nota',
  'No encontramos pasajes para esa busqueda.',
  true
where not exists (
  select 1 from public.devotional_screen_content
);

insert into public.devotional_passages (title, description, passage_reference, viewer_url, external_url, sort_order, is_active)
select 'La Palabra como guia', 'Devocional para meditar en la direccion de Dios.', 'Salmo 119:105', 'https://www.bible.com/es/bible/149/PSA.119.105.RVR1960', 'https://www.bible.com/es/bible/149/PSA.119.105.RVR1960', 1, true
where not exists (select 1 from public.devotional_passages where passage_reference = 'Salmo 119:105');

insert into public.devotional_passages (title, description, passage_reference, viewer_url, external_url, sort_order, is_active)
select 'Nuevo nacimiento', 'Devocional sobre la vida nueva en Cristo.', 'Juan 3:16', 'https://www.bible.com/es/bible/149/JHN.3.16.RVR1960', 'https://www.bible.com/es/bible/149/JHN.3.16.RVR1960', 2, true
where not exists (select 1 from public.devotional_passages where passage_reference = 'Juan 3:16');

insert into public.devotional_passages (title, description, passage_reference, viewer_url, external_url, sort_order, is_active)
select 'Permanecer en Cristo', 'Devocional para revisar fruto, dependencia y comunion.', 'Juan 15', 'https://www.bible.com/es/bible/149/JHN.15.RVR1960', 'https://www.bible.com/es/bible/149/JHN.15.RVR1960', 3, true
where not exists (select 1 from public.devotional_passages where passage_reference = 'Juan 15');
