create table if not exists public.discipleship_notes_content (
  id bigint generated by default as identity primary key,
  title text,
  subtitle text,
  title_placeholder text,
  body_placeholder text,
  button_text text,
  empty_text text,
  is_active boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.discipleship_notes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text,
  body text not null,
  note_date date not null default ((now() at time zone 'America/Bogota')::date),
  is_active boolean not null default true,
  created_at timestamptz default now(),
  updated_at timestamptz not null default now()
);

alter table public.discipleship_notes
add column if not exists is_active boolean not null default true;

alter table public.discipleship_notes
add column if not exists updated_at timestamptz not null default now();

alter table public.discipleship_notes_content enable row level security;
alter table public.discipleship_notes enable row level security;

drop policy if exists "discipleship_notes_content_read_active" on public.discipleship_notes_content;
create policy "discipleship_notes_content_read_active"
on public.discipleship_notes_content for select
to authenticated
using (is_active = true);

drop policy if exists "discipleship_notes_select_own" on public.discipleship_notes;
create policy "discipleship_notes_select_own"
on public.discipleship_notes for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "discipleship_notes_insert_own" on public.discipleship_notes;
create policy "discipleship_notes_insert_own"
on public.discipleship_notes for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "discipleship_notes_update_own" on public.discipleship_notes;
create policy "discipleship_notes_update_own"
on public.discipleship_notes for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "discipleship_notes_delete_own" on public.discipleship_notes;

update public.discipleship_modules
set route = '/discipulado/notas'
where title = 'Notas';

insert into public.discipleship_notes_content (title, subtitle, title_placeholder, body_placeholder, button_text, empty_text, is_active)
select
  'Notas personales',
  'Guarda apuntes privados de tu proceso de discipulado.',
  'Titulo opcional',
  'Escribe tu nota...',
  'Guardar nota',
  'Aun no tienes notas guardadas.',
  true
where not exists (
  select 1 from public.discipleship_notes_content
);
