insert into storage.buckets (id, name, public)
values ('discipleship-materials', 'discipleship-materials', false)
on conflict (id) do update set public = false;

create table if not exists public.discipleship_materials (
  id bigint generated by default as identity primary key,
  title text,
  description text,
  bucket_id text not null default 'discipleship-materials',
  storage_path text not null,
  allowed_role text not null default 'lider',
  sort_order int default 0,
  is_active boolean default true,
  created_at timestamptz default now()
);

alter table public.discipleship_materials enable row level security;

drop policy if exists "discipleship_materials_read_by_role" on public.discipleship_materials;
create policy "discipleship_materials_read_by_role"
on public.discipleship_materials for select
to authenticated
using (
  is_active = true
  and exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
    and profiles.role = discipleship_materials.allowed_role
  )
);

drop policy if exists "discipleship_material_files_read_by_lider" on storage.objects;
create policy "discipleship_material_files_read_by_lider"
on storage.objects for select
to authenticated
using (
  bucket_id = 'discipleship-materials'
  and exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
    and profiles.role = 'lider'
  )
);

update public.discipleship_modules
set route = '/discipulado/material'
where title = 'Material';

insert into public.discipleship_materials (title, description, bucket_id, storage_path, allowed_role, sort_order, is_active)
select
  'Cartilla de Discipulado Personal',
  'Material de formacion para lideres.',
  'discipleship-materials',
  'cartilla-discipulado-personal.pdf',
  'lider',
  1,
  true
where not exists (
  select 1
  from public.discipleship_materials
  where storage_path = 'cartilla-discipulado-personal.pdf'
);
