create table if not exists public.giving_accounts (
  id bigint generated by default as identity primary key,
  menu_title text,
  screen_title text,
  subtitle text,
  qr_image_url text,
  account_type text,
  bank_name text,
  account_number text,
  tax_id_label text,
  tax_id_value text,
  is_active boolean default true,
  created_at timestamptz default now()
);

alter table public.giving_accounts enable row level security;

drop policy if exists "giving_accounts_read_active" on public.giving_accounts;
create policy "giving_accounts_read_active"
on public.giving_accounts for select
to authenticated
using (is_active = true);

insert into public.giving_accounts (
  menu_title,
  screen_title,
  subtitle,
  qr_image_url,
  account_type,
  bank_name,
  account_number,
  tax_id_label,
  tax_id_value,
  is_active
)
select
  'Cuenta para diezmos y ofrendas',
  'Cuenta para diezmos, ofrendas y compromisos',
  'Puedes realizar tus aportes usando el QR o los datos de la cuenta.',
  null,
  'Ahorros',
  'Bancolombia',
  '33100003454',
  'NIT',
  '900217901',
  true
where not exists (
  select 1
  from public.giving_accounts
);
