create table if not exists public.home_featured_song (
  id bigint generated by default as identity primary key,
  title text not null,
  artist text,
  audio_preview_url text not null,
  cover_url text,
  reference_url text,
  preview_duration_seconds int not null default 60
    constraint home_featured_song_duration_check
    check (preview_duration_seconds between 1 and 60),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.home_featured_song enable row level security;

drop policy if exists "home_featured_song_read_active" on public.home_featured_song;
create policy "home_featured_song_read_active"
on public.home_featured_song for select
to authenticated
using (is_active = true);

drop policy if exists "home_featured_song_admin_all" on public.home_featured_song;
create policy "home_featured_song_admin_all"
on public.home_featured_song for all
to authenticated
using (public.current_user_is_super_admin())
with check (public.current_user_is_super_admin());
