alter table public.home_banners
add column if not exists badge_text text,
add column if not exists image_url text;

alter table public.events
add column if not exists background_color text,
add column if not exists accent_color text,
add column if not exists image_url text,
add column if not exists show_on_home boolean default false,
add column if not exists home_sort_order int default 0;

create table if not exists public.home_quick_links (
  id bigint generated by default as identity primary key,
  title text,
  route text,
  icon_name text,
  background_color text,
  accent_color text,
  sort_order int default 0,
  is_active boolean default true,
  created_at timestamptz default now()
);

alter table public.home_quick_links enable row level security;

drop policy if exists "home_quick_links_read_active" on public.home_quick_links;
create policy "home_quick_links_read_active"
on public.home_quick_links for select
to authenticated
using (is_active = true);

update public.home_header
set
  app_label = 'Vendimia',
  title = 'Bienvenido a Vendimia',
  subtitle = 'Conectados para crecer en Cristo',
  avatar_text = null
where is_active = true;

update public.home_banners
set
  title = 'Campamento de Jovenes',
  subtitle = '5 Abril 2025',
  button_text = 'Ver detalles',
  button_route = '/(tabs)/events',
  background_color = '#9A4F08',
  accent_color = '#F9820B',
  image_url = 'https://images.unsplash.com/photo-1507692049790-de58290a4334?auto=format&fit=crop&w=1200&q=80',
  badge_text = 'Febrero'
where id in (
  select id from public.home_banners order by sort_order asc, id asc limit 1
);

insert into public.home_sections (section_key, title, action_text, sort_order, is_active)
select 'quick_links', 'Accesos rapidos', null, 0, true
where not exists (select 1 from public.home_sections where section_key = 'quick_links');

insert into public.home_sections (section_key, title, action_text, sort_order, is_active)
select 'upcoming_events', 'Proximos eventos', null, 1, true
where not exists (select 1 from public.home_sections where section_key = 'upcoming_events');

insert into public.home_quick_links (title, route, icon_name, background_color, accent_color, sort_order, is_active)
select 'Discipulado', '/(tabs)/discipulado', 'book', '#1F1F1F', '#F9820B', 1, true
where not exists (select 1 from public.home_quick_links where route = '/(tabs)/discipulado');

insert into public.home_quick_links (title, route, icon_name, background_color, accent_color, sort_order, is_active)
select 'Oracion', '/(tabs)/prayer', 'heart', '#1F1F1F', '#F9820B', 2, true
where not exists (select 1 from public.home_quick_links where route = '/(tabs)/prayer');

insert into public.home_quick_links (title, route, icon_name, background_color, accent_color, sort_order, is_active)
select 'Eventos', '/(tabs)/events', 'calendar', '#1F1F1F', '#F9820B', 3, true
where not exists (select 1 from public.home_quick_links where route = '/(tabs)/events');

insert into public.home_quick_links (title, route, icon_name, background_color, accent_color, sort_order, is_active)
select 'Informacion', '/(tabs)/more/info', 'information-circle', '#1F1F1F', '#F9820B', 4, true
where not exists (select 1 from public.home_quick_links where route = '/(tabs)/more/info');

update public.home_quick_links
set
  title = 'Información',
  route = '/(tabs)/more/info',
  icon_name = 'information-circle'
where title = 'Avisos' or route = '/(tabs)/more';

update public.events
set
  background_color = coalesce(background_color, '#3A1F2A'),
  accent_color = coalesce(accent_color, '#F9820B'),
  image_url = coalesce(image_url, 'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?auto=format&fit=crop&w=900&q=80')
where is_active = true;

with ranked_events as (
  select id, row_number() over (order by event_date asc, id asc) as rn
  from public.events
  where is_active = true
  and event_date >= (now() at time zone 'America/Bogota')::date
)
update public.events
set
  show_on_home = ranked_events.rn <= 2,
  home_sort_order = ranked_events.rn
from ranked_events
where events.id = ranked_events.id;
