create table if not exists public.leadership_schedule_header (
  id bigint generated by default as identity primary key,
  menu_title text,
  screen_title text,
  side_label text,
  subtitle text,
  is_active boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.leadership_schedule_items (
  id bigint generated by default as identity primary key,
  title text,
  description text,
  sort_order int default 0,
  is_active boolean default true,
  created_at timestamptz default now()
);

alter table public.leadership_schedule_header enable row level security;
alter table public.leadership_schedule_items enable row level security;

drop policy if exists "leadership_schedule_header_read_active" on public.leadership_schedule_header;
create policy "leadership_schedule_header_read_active"
on public.leadership_schedule_header for select
to authenticated
using (is_active = true);

drop policy if exists "leadership_schedule_items_read_active" on public.leadership_schedule_items;
create policy "leadership_schedule_items_read_active"
on public.leadership_schedule_items for select
to authenticated
using (is_active = true);

insert into public.leadership_schedule_header (menu_title, screen_title, side_label, subtitle, is_active)
select 'Cronograma Liderazgo', 'Programacion', '30 NOV', null, true
where not exists (select 1 from public.leadership_schedule_header);

insert into public.leadership_schedule_items (title, description, sort_order, is_active)
select *
from (
  values
    ('Sky Staff', 'Eliana, Angie, Lina y Laura', 1, true),
    ('Equipo Worship', 'Dirige Cata', 2, true),
    ('Diezmos y ofrendas', 'Anderson, Diana y Psa. Stella', 3, true),
    ('Iglesia Infantil', 'Andrea', 4, true),
    ('Preadolescentes', 'No habra clases', 5, true),
    ('Bienvenida', 'Alejandro', 6, true),
    ('Anuncios', 'No habran', 7, true),
    ('Medios', 'Diapositivas: Anderson y Michelle' || chr(10) || 'Transmision: No habra', 8, true),
    ('Ventas', 'Rodolfo y Leonardo', 9, true)
) as seed(title, description, sort_order, is_active)
where not exists (select 1 from public.leadership_schedule_items);
