-- Catalogo central de notificaciones automaticas.
-- Ejecutar una sola vez en Supabase/Navicat. Los inserts son idempotentes.

create table if not exists public.notification_master (
  id bigint generated by default as identity primary key,
  notification_key text not null unique,
  category text not null,
  name text not null,
  trigger_type text not null check (trigger_type in ('immediate', 'scheduled', 'conditional', 'manual')),
  audience_type text not null check (audience_type in ('all', 'user', 'role', 'appointment_managers', 'event_attendees', 'assigned_user')),
  target_role text,
  priority text not null default 'medium' check (priority in ('low', 'medium', 'high')),
  title_template text not null,
  body_template text not null,
  route text,
  offset_minutes integer,
  schedule_config jsonb not null default '{}'::jsonb,
  implementation_status text not null default 'planned' check (implementation_status in ('ready', 'planned')),
  is_active boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.notification_jobs (
  id bigint generated by default as identity primary key,
  master_id bigint not null references public.notification_master(id) on delete cascade,
  recipient_user_id uuid references auth.users(id) on delete cascade,
  source_type text,
  source_id text,
  variables jsonb not null default '{}'::jsonb,
  scheduled_for timestamptz not null default now(),
  status text not null default 'pending' check (status in ('pending', 'processing', 'sent', 'failed', 'cancelled')),
  attempts integer not null default 0,
  idempotency_key text not null unique,
  last_error text,
  processed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.notifications
add column if not exists master_id bigint references public.notification_master(id) on delete set null;

alter table public.notifications
add column if not exists target_user_id uuid references auth.users(id) on delete set null;

alter table public.notifications
add column if not exists route text;

alter table public.notifications
add column if not exists data jsonb not null default '{}'::jsonb;

alter table public.notification_master enable row level security;
alter table public.notification_jobs enable row level security;

drop policy if exists "notification_master_select_super_admin" on public.notification_master;
create policy "notification_master_select_super_admin"
on public.notification_master for select
to authenticated
using (
  exists (
    select 1 from public.profiles
    where profiles.id = auth.uid()
    and profiles.role = 'super_admin'
  )
);

drop policy if exists "notification_master_insert_super_admin" on public.notification_master;
create policy "notification_master_insert_super_admin"
on public.notification_master for insert
to authenticated
with check (
  exists (
    select 1 from public.profiles
    where profiles.id = auth.uid()
    and profiles.role = 'super_admin'
  )
);

drop policy if exists "notification_master_update_super_admin" on public.notification_master;
create policy "notification_master_update_super_admin"
on public.notification_master for update
to authenticated
using (
  exists (
    select 1 from public.profiles
    where profiles.id = auth.uid()
    and profiles.role = 'super_admin'
  )
)
with check (
  exists (
    select 1 from public.profiles
    where profiles.id = auth.uid()
    and profiles.role = 'super_admin'
  )
);

drop policy if exists "notification_jobs_select_super_admin" on public.notification_jobs;
create policy "notification_jobs_select_super_admin"
on public.notification_jobs for select
to authenticated
using (
  exists (
    select 1 from public.profiles
    where profiles.id = auth.uid()
    and profiles.role = 'super_admin'
  )
);

insert into public.notification_master (
  notification_key, category, name, trigger_type, audience_type, target_role, priority,
  title_template, body_template, route, offset_minutes, schedule_config,
  implementation_status, is_active
)
values
  ('event_24h', 'Eventos', 'Evento proximo 24h', 'scheduled', 'all', null, 'high',
   'Tu evento es manana', 'No olvides que manana tienes {nombre_evento} a las {hora}. Te esperamos.',
   '/(tabs)/events', -1440, '{}'::jsonb, 'planned', false),
  ('event_2h', 'Eventos', 'Evento proximo 2h', 'scheduled', 'all', null, 'high',
   'Faltan 2 horas', 'En 2 horas inicia {nombre_evento}. Nos vemos en {ubicacion}.',
   '/(tabs)/events', -120, '{}'::jsonb, 'planned', false),
  ('event_changed', 'Eventos', 'Cambio o cancelacion de evento', 'immediate', 'all', null, 'high',
   'Cambios en un evento', 'El evento {nombre_evento} ha sido actualizado. Revisa los nuevos detalles en la app.',
   '/(tabs)/events', null, '{}'::jsonb, 'planned', false),
  ('daily_devotional_available', 'Devocionales', 'Devocional diario disponible', 'immediate', 'all', null, 'high',
   'Devocional disponible', 'Ya esta disponible el devocional de hoy. Dedica unos minutos para crecer en tu relacion con Dios.',
   '/(tabs)/discipulado/devocionales', null, '{}'::jsonb, 'ready', true),
  ('daily_devotional_reminder', 'Devocionales', 'Recordatorio de devocional', 'conditional', 'user', null, 'high',
   'Ya tuviste tu tiempo con Dios?', 'Aun no registras tu devocional de hoy. Nunca es tarde para acercarte al Senor.',
   '/(tabs)/discipulado/devocionales', null, '{"hour":19,"timezone":"America/Bogota"}'::jsonb, 'planned', false),
  ('appointment_received', 'Citas Pastorales', 'Solicitud recibida', 'immediate', 'user', null, 'medium',
   'Solicitud recibida', 'Hemos recibido tu solicitud de cita pastoral para el {fecha} a las {hora}.',
   '/(tabs)/more/appointments', null, '{}'::jsonb, 'ready', true),
  ('appointment_accepted', 'Citas Pastorales', 'Cita aceptada', 'immediate', 'user', null, 'high',
   'Tu cita fue confirmada', 'Tu cita pastoral ha sido aceptada para el {fecha} a las {hora}.',
   '/(tabs)/more/appointments', null, '{}'::jsonb, 'ready', true),
  ('appointment_rejected', 'Citas Pastorales', 'Cita rechazada', 'immediate', 'user', null, 'high',
   'Actualizacion de tu cita', 'Tu solicitud de cita no pudo ser programada. Revisa la respuesta enviada por el equipo pastoral.',
   '/(tabs)/more/appointments', null, '{}'::jsonb, 'ready', true),
  ('appointment_response_updated', 'Citas Pastorales', 'Actualizacion de respuesta', 'immediate', 'user', null, 'medium',
   'Nueva respuesta a tu solicitud', 'Tu solicitud de cita pastoral recibio una actualizacion. Ingresa a la app para verla.',
   '/(tabs)/more/appointments', null, '{}'::jsonb, 'ready', true),
  ('appointment_24h', 'Citas Pastorales', 'Recordatorio 24h antes', 'scheduled', 'user', null, 'high',
   'Tu cita es manana', 'Te recordamos que tienes una cita pastoral manana a las {hora}.',
   '/(tabs)/more/appointments', -1440, '{}'::jsonb, 'planned', false),
  ('appointment_2h', 'Citas Pastorales', 'Recordatorio 2h antes', 'scheduled', 'user', null, 'high',
   'Tu cita esta cerca', 'Faltan 2 horas para tu cita pastoral. Te esperamos.',
   '/(tabs)/more/appointments', -120, '{}'::jsonb, 'planned', false),
  ('appointment_pending_user', 'Citas Pastorales', 'Solicitud sin respuesta', 'conditional', 'user', null, 'low',
   'Seguimos revisando tu solicitud', 'Tu solicitud aun esta siendo revisada. Gracias por tu paciencia y comprension.',
   '/(tabs)/more/appointments', -1440, '{}'::jsonb, 'planned', false),
  ('appointment_new_manager', 'Citas Pastorales', 'Nueva solicitud', 'immediate', 'appointment_managers', null, 'high',
   'Nueva cita pastoral', 'Se ha recibido una nueva solicitud de cita pastoral pendiente de revision.',
   '/(tabs)/more/appointment-responses', null, '{}'::jsonb, 'ready', true),
  ('appointment_pending_summary', 'Citas Pastorales', 'Resumen diario de pendientes', 'conditional', 'appointment_managers', null, 'medium',
   'Citas pendientes', 'Tienes {cantidad} solicitudes de cita pastoral pendientes por revisar.',
   '/(tabs)/more/appointment-responses', null, '{"hour":8,"timezone":"America/Bogota"}'::jsonb, 'planned', false),
  ('appointment_urgent_manager', 'Citas Pastorales', 'Solicitud proxima sin gestionar', 'conditional', 'appointment_managers', null, 'high',
   'Solicitud urgente', 'Una cita solicitada ocurrira pronto y aun no ha sido gestionada.',
   '/(tabs)/more/appointment-responses', -1440, '{}'::jsonb, 'planned', false),
  ('appointment_schedule_conflict', 'Citas Pastorales', 'Conflicto de horario', 'conditional', 'appointment_managers', null, 'medium',
   'Posible conflicto de agenda', 'Se detecto otra solicitud para el mismo horario. Revisa la programacion.',
   '/(tabs)/more/appointment-responses', null, '{}'::jsonb, 'planned', false),
  ('appointment_today_summary', 'Citas Pastorales', 'Resumen de citas del dia', 'scheduled', 'appointment_managers', null, 'medium',
   'Agenda pastoral de hoy', 'Hoy tienes {cantidad} citas pastorales confirmadas.',
   '/(tabs)/more/appointment-responses', null, '{"hour":7,"timezone":"America/Bogota"}'::jsonb, 'planned', false),
  ('prayer_support_summary', 'Oracion', 'Motivo de oracion apoyado', 'conditional', 'user', null, 'medium',
   'No estas solo', '{cantidad} personas estan orando por tu peticion. Dios escucha cada oracion.',
   '/(tabs)/prayer', null, '{}'::jsonb, 'planned', false),
  ('prayer_new_request', 'Oracion', 'Nuevo motivo de oracion', 'immediate', 'all', null, 'medium',
   'Nueva peticion de oracion', 'Un miembro de la iglesia ha compartido una nueva peticion de oracion.',
   '/(tabs)/prayer', null, '{}'::jsonb, 'planned', false),
  ('discipleship_weekly_reading', 'Discipulado', 'Recordatorio semanal de lectura', 'scheduled', 'all', null, 'medium',
   'Continua tu crecimiento', 'Es momento de seguir avanzando en tu lectura y discipulado. No te detengas.',
   '/(tabs)/discipulado', null, '{"weekday":1,"hour":9,"timezone":"America/Bogota"}'::jsonb, 'planned', false),
  ('discipleship_new_material', 'Discipulado', 'Nuevo material disponible', 'immediate', 'role', 'lider', 'medium',
   'Nuevo material disponible', 'Se ha publicado nuevo contenido de discipulado para continuar tu formacion.',
   '/(tabs)/discipulado/material', null, '{}'::jsonb, 'planned', false),
  ('leadership_new_schedule', 'Liderazgo', 'Nueva programacion', 'immediate', 'role', 'lider', 'medium',
   'Nueva asignacion de servicio', 'Se te ha asignado una nueva responsabilidad dentro del ministerio.',
   '/(tabs)/more/leadership-schedule', null, '{}'::jsonb, 'planned', false),
  ('leadership_service_reminder', 'Liderazgo', 'Recordatorio de responsabilidad', 'scheduled', 'assigned_user', null, 'medium',
   'Tu servicio es manana', 'Te recordamos tu responsabilidad asignada para el proximo servicio.',
   '/(tabs)/more/leadership-schedule', -1440, '{}'::jsonb, 'planned', false),
  ('general_announcement', 'Anuncios', 'Anuncio general', 'manual', 'all', null, 'high',
   'Nuevo anuncio de la iglesia', 'Tenemos informacion importante para ti. Consulta el anuncio completo en la app.',
   '/(tabs)', null, '{}'::jsonb, 'ready', true),
  ('account_registered', 'Seguridad', 'Registro exitoso', 'immediate', 'user', null, 'low',
   'Bienvenido a Vendimia', 'Tu cuenta ha sido creada correctamente. Estamos felices de acompanarte en este camino.',
   '/(tabs)', null, '{}'::jsonb, 'planned', false),
  ('account_password_changed', 'Seguridad', 'Cambio de contrasena', 'immediate', 'user', null, 'high',
   'Contrasena actualizada', 'Tu contrasena fue cambiada exitosamente. Si no realizaste esta accion, contactanos.',
   '/(tabs)/more/profile', null, '{}'::jsonb, 'planned', false),
  ('account_contact_changed', 'Seguridad', 'Cambio de correo o telefono', 'immediate', 'user', null, 'high',
   'Datos actualizados', 'Tu informacion de contacto fue actualizada correctamente.',
   '/(tabs)/more/profile', null, '{}'::jsonb, 'planned', false),
  ('account_new_device', 'Seguridad', 'Inicio de sesion en nuevo dispositivo', 'immediate', 'user', null, 'medium',
   'Nuevo acceso detectado', 'Detectamos un inicio de sesion desde un dispositivo nuevo.',
   '/(tabs)/more/profile', null, '{}'::jsonb, 'planned', false),
  ('admin_pending_content', 'Administracion', 'Contenido pendiente', 'conditional', 'role', 'super_admin', 'medium',
   'Acciones pendientes', 'Existen elementos que requieren tu atencion en el panel administrativo.',
   '/(tabs)/more/admin-notifications', null, '{"hour":8,"timezone":"America/Bogota"}'::jsonb, 'planned', false)
on conflict (notification_key) do update set
  category = excluded.category,
  name = excluded.name,
  trigger_type = excluded.trigger_type,
  audience_type = excluded.audience_type,
  target_role = excluded.target_role,
  priority = excluded.priority,
  title_template = excluded.title_template,
  body_template = excluded.body_template,
  route = excluded.route,
  offset_minutes = excluded.offset_minutes,
  schedule_config = excluded.schedule_config,
  implementation_status = excluded.implementation_status,
  updated_at = now();
