-- Sistema de notificaciones push para Vendimia App 2.0.
-- Rol administrador poderoso: public.profiles.role = 'super_admin'

create table if not exists public.user_push_tokens (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  expo_push_token text not null unique,
  platform text,
  app_ownership text,
  device_name text,
  project_id text,
  is_active boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.user_push_tokens
add column if not exists app_ownership text;

alter table public.user_push_tokens
add column if not exists device_name text;

alter table public.user_push_tokens
add column if not exists project_id text;

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  title text not null,
  body text not null,
  target_role text,
  notification_type text not null default 'manual',
  scheduled_for timestamptz,
  sent_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz default now()
);

create table if not exists public.notification_deliveries (
  id bigint generated by default as identity primary key,
  notification_id bigint references public.notifications(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  expo_push_token text not null,
  status text not null default 'pending',
  response jsonb,
  created_at timestamptz default now()
);

alter table public.user_push_tokens enable row level security;
alter table public.notifications enable row level security;
alter table public.notification_deliveries enable row level security;

drop policy if exists "user_push_tokens_select_own" on public.user_push_tokens;
create policy "user_push_tokens_select_own"
on public.user_push_tokens for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "user_push_tokens_insert_own" on public.user_push_tokens;
create policy "user_push_tokens_insert_own"
on public.user_push_tokens for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "user_push_tokens_update_own" on public.user_push_tokens;
create policy "user_push_tokens_update_own"
on public.user_push_tokens for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "notifications_select_super_admin" on public.notifications;
create policy "notifications_select_super_admin"
on public.notifications for select
to authenticated
using (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
    and profiles.role = 'super_admin'
  )
);

drop policy if exists "notification_deliveries_select_super_admin" on public.notification_deliveries;
create policy "notification_deliveries_select_super_admin"
on public.notification_deliveries for select
to authenticated
using (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
    and profiles.role = 'super_admin'
  )
);

-- Para convertir un usuario en administrador poderoso:
-- update public.profiles set role = 'super_admin' where email = 'correo@dominio.com';
