-- Citas pastorales y telefono obligatorio.
-- Ejecutar en Supabase SQL editor antes de publicar la build.

alter table public.profiles
add column if not exists phone_country_code text;

alter table public.profiles
add column if not exists phone_number text;

alter table public.profiles
add column if not exists can_manage_appointments boolean not null default false;

create unique index if not exists profiles_phone_unique
on public.profiles (phone_country_code, phone_number)
where phone_country_code is not null and phone_number is not null;

grant update (full_name, email, avatar_url, phone_country_code, phone_number) on public.profiles to authenticated;

create table if not exists public.phone_country_codes (
  id bigint generated by default as identity primary key,
  country_name text not null,
  country_code text not null,
  sort_order int default 0,
  is_active boolean default true
);

insert into public.phone_country_codes (country_name, country_code, sort_order, is_active)
values
  ('Colombia', '+57', 1, true),
  ('Estados Unidos', '+1', 2, true),
  ('Mexico', '+52', 3, true),
  ('Argentina', '+54', 4, true),
  ('Chile', '+56', 5, true),
  ('Peru', '+51', 6, true),
  ('Ecuador', '+593', 7, true),
  ('Venezuela', '+58', 8, true)
on conflict do nothing;

create table if not exists public.pastor_appointments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  appointment_date date not null,
  appointment_time time not null,
  reason text not null,
  status text not null default 'enviado' check (status in ('enviado', 'pendiente', 'aceptada', 'rechazada')),
  response_message text,
  responded_by uuid references auth.users(id) on delete set null,
  responded_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create or replace function public.find_email_by_phone(input_country_code text, input_phone_number text)
returns text
language sql
security definer
set search_path = public
stable
as $$
  select email
  from public.profiles
  where phone_country_code = trim(input_country_code)
  and regexp_replace(coalesce(phone_number, ''), '\D', '', 'g') = regexp_replace(coalesce(input_phone_number, ''), '\D', '', 'g')
  limit 1
$$;

grant execute on function public.find_email_by_phone(text, text) to anon, authenticated;

create or replace function public.current_user_can_manage_appointments()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select coalesce((
    select can_manage_appointments
    from public.profiles
    where id = auth.uid()
    limit 1
  ), false)
$$;

grant execute on function public.current_user_can_manage_appointments() to authenticated;

alter table public.phone_country_codes enable row level security;
alter table public.pastor_appointments enable row level security;

drop policy if exists "phone_country_codes_read_active" on public.phone_country_codes;
create policy "phone_country_codes_read_active"
on public.phone_country_codes for select
to anon, authenticated
using (is_active = true);

drop policy if exists "profiles_select_appointment_manager" on public.profiles;
create policy "profiles_select_appointment_manager"
on public.profiles for select
to authenticated
using (public.current_user_can_manage_appointments());

drop policy if exists "pastor_appointments_select_own_or_manager" on public.pastor_appointments;
create policy "pastor_appointments_select_own_or_manager"
on public.pastor_appointments for select
to authenticated
using (
  auth.uid() = user_id
  or public.current_user_can_manage_appointments()
);

drop policy if exists "pastor_appointments_insert_own" on public.pastor_appointments;
create policy "pastor_appointments_insert_own"
on public.pastor_appointments for insert
to authenticated
with check (
  auth.uid() = user_id
  and status = 'enviado'
  and response_message is null
  and responded_by is null
  and responded_at is null
);

drop policy if exists "pastor_appointments_update_manager" on public.pastor_appointments;
create policy "pastor_appointments_update_manager"
on public.pastor_appointments for update
to authenticated
using (public.current_user_can_manage_appointments())
with check (public.current_user_can_manage_appointments());

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, email, phone_country_code, phone_number)
  values (
    new.id,
    coalesce(nullif(new.raw_user_meta_data->>'full_name', ''), split_part(new.email, '@', 1)),
    new.email,
    nullif(new.raw_user_meta_data->>'phone_country_code', ''),
    nullif(new.raw_user_meta_data->>'phone_number', '')
  );
  return new;
end;
$$;

create or replace function public.log_profile_changes()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if old.full_name is distinct from new.full_name then
    insert into public.profile_change_logs (user_id, changed_by, field_name, old_value, new_value)
    values (new.id, auth.uid(), 'full_name', old.full_name, new.full_name);
  end if;

  if old.email is distinct from new.email then
    insert into public.profile_change_logs (user_id, changed_by, field_name, old_value, new_value)
    values (new.id, auth.uid(), 'email', old.email, new.email);
  end if;

  if old.phone_country_code is distinct from new.phone_country_code then
    insert into public.profile_change_logs (user_id, changed_by, field_name, old_value, new_value)
    values (new.id, auth.uid(), 'phone_country_code', old.phone_country_code, new.phone_country_code);
  end if;

  if old.phone_number is distinct from new.phone_number then
    insert into public.profile_change_logs (user_id, changed_by, field_name, old_value, new_value)
    values (new.id, auth.uid(), 'phone_number', old.phone_number, new.phone_number);
  end if;

  if old.avatar_url is distinct from new.avatar_url then
    insert into public.profile_change_logs (user_id, changed_by, field_name, old_value, new_value)
    values (new.id, auth.uid(), 'avatar_url', old.avatar_url, new.avatar_url);
  end if;

  return new;
end;
$$;

drop trigger if exists on_profile_updated_log_changes on public.profiles;

create trigger on_profile_updated_log_changes
after update of full_name, email, phone_country_code, phone_number, avatar_url on public.profiles
for each row execute function public.log_profile_changes();

-- Habilitar usuarios que pueden responder citas:
-- update public.profiles
-- set can_manage_appointments = true
-- where email = 'pastor@dominio.com';
