create table if not exists public.prayer_request_action_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  request_id bigint references public.prayer_requests(id) on delete set null,
  action text not null,
  status text not null,
  error_message text,
  metadata jsonb default '{}'::jsonb,
  created_at timestamptz default now(),
  constraint prayer_request_action_logs_status_check
    check (status in ('success', 'error', 'not_found'))
);

alter table public.prayer_request_action_logs enable row level security;

grant select, insert on public.prayer_request_action_logs to authenticated;

drop policy if exists "prayer_request_action_logs_insert_own" on public.prayer_request_action_logs;
create policy "prayer_request_action_logs_insert_own"
on public.prayer_request_action_logs for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "prayer_request_action_logs_select_own" on public.prayer_request_action_logs;
create policy "prayer_request_action_logs_select_own"
on public.prayer_request_action_logs for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "prayer_request_action_logs_select_super_admin" on public.prayer_request_action_logs;
create policy "prayer_request_action_logs_select_super_admin"
on public.prayer_request_action_logs for select
to authenticated
using (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and profiles.role = 'super_admin'
  )
);

create or replace function public.mark_prayer_request_answered(target_request_id bigint)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  affected_rows int;
begin
  update public.prayer_requests
  set is_active = false
  where id = target_request_id
    and user_id = auth.uid()
    and is_active = true;

  get diagnostics affected_rows = row_count;

  if affected_rows = 0 then
    insert into public.prayer_request_action_logs (
      user_id,
      request_id,
      action,
      status,
      error_message,
      metadata
    )
    values (
      auth.uid(),
      target_request_id,
      'mark_answered',
      'not_found',
      'No active prayer request found for this authenticated user.',
      jsonb_build_object('source', 'rpc')
    );

    return false;
  end if;

  insert into public.prayer_request_action_logs (
    user_id,
    request_id,
    action,
    status,
    metadata
  )
  values (
    auth.uid(),
    target_request_id,
    'mark_answered',
    'success',
    jsonb_build_object('source', 'rpc')
  );

  return true;
exception
  when others then
    insert into public.prayer_request_action_logs (
      user_id,
      request_id,
      action,
      status,
      error_message,
      metadata
    )
    values (
      auth.uid(),
      target_request_id,
      'mark_answered',
      'error',
      sqlerrm,
      jsonb_build_object('source', 'rpc', 'sqlstate', sqlstate)
    );

    raise;
end;
$$;

grant execute on function public.mark_prayer_request_answered(bigint) to authenticated;
