create table if not exists public.prayer_screen_content (
  id bigint generated by default as identity primary key,
  title text,
  subtitle text,
  input_placeholder text,
  button_text text,
  empty_text text,
  like_text text,
  unlike_text text,
  is_active boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.prayer_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  body text not null,
  is_active boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.prayer_request_likes (
  id bigint generated by default as identity primary key,
  request_id bigint not null references public.prayer_requests(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz default now(),
  constraint prayer_request_likes_request_user_unique unique (request_id, user_id)
);

alter table public.prayer_screen_content enable row level security;
alter table public.prayer_requests enable row level security;
alter table public.prayer_request_likes enable row level security;

drop policy if exists "prayer_screen_content_read_active" on public.prayer_screen_content;
create policy "prayer_screen_content_read_active"
on public.prayer_screen_content for select
to authenticated
using (is_active = true);

drop policy if exists "prayer_requests_read_active" on public.prayer_requests;
create policy "prayer_requests_read_active"
on public.prayer_requests for select
to authenticated
using (is_active = true);

drop policy if exists "prayer_requests_insert_own" on public.prayer_requests;
create policy "prayer_requests_insert_own"
on public.prayer_requests for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "prayer_requests_update_own" on public.prayer_requests;
create policy "prayer_requests_update_own"
on public.prayer_requests for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "prayer_request_likes_read" on public.prayer_request_likes;
create policy "prayer_request_likes_read"
on public.prayer_request_likes for select
to authenticated
using (true);

drop policy if exists "prayer_request_likes_insert_own" on public.prayer_request_likes;
create policy "prayer_request_likes_insert_own"
on public.prayer_request_likes for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "prayer_request_likes_delete_own" on public.prayer_request_likes;
create policy "prayer_request_likes_delete_own"
on public.prayer_request_likes for delete
to authenticated
using (auth.uid() = user_id);

insert into public.prayer_screen_content (title, subtitle, input_placeholder, button_text, empty_text, like_text, unlike_text, is_active)
select 'Oración', 'Comparte tus motivos y acompaña en oración a la comunidad.', 'Escribe tu motivo de oración...', 'Publicar motivo', 'Aún no hay motivos de oración publicados.', 'Estoy orando', 'Orando', true
where not exists (
  select 1 from public.prayer_screen_content
);
