alter table public.profiles
add column if not exists avatar_url text;

revoke update on public.profiles from authenticated;
grant update (full_name, email, avatar_url) on public.profiles to authenticated;

create table if not exists public.profile_change_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  changed_by uuid references auth.users(id) on delete set null,
  field_name text not null,
  old_value text,
  new_value text,
  created_at timestamptz default now()
);

grant select, insert on public.profile_change_logs to authenticated;

alter table public.profile_change_logs enable row level security;

drop policy if exists "profile_change_logs_select_own" on public.profile_change_logs;
create policy "profile_change_logs_select_own"
on public.profile_change_logs for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "profile_change_logs_insert_own_password" on public.profile_change_logs;
create policy "profile_change_logs_insert_own_password"
on public.profile_change_logs for insert
to authenticated
with check (
  auth.uid() = user_id
  and auth.uid() = changed_by
  and field_name = 'password'
);

create or replace function public.log_profile_changes()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if old.full_name is distinct from new.full_name then
    insert into public.profile_change_logs (user_id, changed_by, field_name, old_value, new_value)
    values (new.id, auth.uid(), 'full_name', old.full_name, new.full_name);
  end if;

  if old.email is distinct from new.email then
    insert into public.profile_change_logs (user_id, changed_by, field_name, old_value, new_value)
    values (new.id, auth.uid(), 'email', old.email, new.email);
  end if;

  if old.avatar_url is distinct from new.avatar_url then
    insert into public.profile_change_logs (user_id, changed_by, field_name, old_value, new_value)
    values (new.id, auth.uid(), 'avatar_url', old.avatar_url, new.avatar_url);
  end if;

  return new;
end;
$$;

drop trigger if exists on_profile_updated_log_changes on public.profiles;

create trigger on_profile_updated_log_changes
after update of full_name, email, avatar_url on public.profiles
for each row execute function public.log_profile_changes();

insert into storage.buckets (id, name, public)
values ('profile-avatars', 'profile-avatars', true)
on conflict (id) do update set public = true;

drop policy if exists "profile_avatars_read" on storage.objects;
create policy "profile_avatars_read"
on storage.objects for select
to authenticated
using (bucket_id = 'profile-avatars');

drop policy if exists "profile_avatars_insert_own" on storage.objects;
create policy "profile_avatars_insert_own"
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'profile-avatars'
  and auth.uid()::text = (storage.foldername(name))[1]
);

drop policy if exists "profile_avatars_update_own" on storage.objects;
create policy "profile_avatars_update_own"
on storage.objects for update
to authenticated
using (
  bucket_id = 'profile-avatars'
  and auth.uid()::text = (storage.foldername(name))[1]
)
with check (
  bucket_id = 'profile-avatars'
  and auth.uid()::text = (storage.foldername(name))[1]
);

drop policy if exists "profile_avatars_delete_own" on storage.objects;
create policy "profile_avatars_delete_own"
on storage.objects for delete
to authenticated
using (
  bucket_id = 'profile-avatars'
  and auth.uid()::text = (storage.foldername(name))[1]
);
