alter table public.profiles
add column if not exists church_attendance_time text;

alter table public.profiles
add column if not exists is_being_discipled boolean;

grant update (
  full_name,
  email,
  avatar_url,
  phone_country_code,
  phone_number,
  church_attendance_time,
  is_being_discipled
) on public.profiles to authenticated;

create table if not exists public.profile_change_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  changed_by uuid references auth.users(id) on delete set null,
  field_name text not null,
  old_value text,
  new_value text,
  created_at timestamptz default now()
);

grant select, insert on public.profile_change_logs to authenticated;

alter table public.profile_change_logs enable row level security;

drop policy if exists "profile_change_logs_select_own" on public.profile_change_logs;
create policy "profile_change_logs_select_own"
on public.profile_change_logs for select
to authenticated
using (auth.uid() = user_id);

create or replace function public.log_profile_changes()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if old.full_name is distinct from new.full_name then
    insert into public.profile_change_logs (user_id, changed_by, field_name, old_value, new_value)
    values (new.id, auth.uid(), 'full_name', old.full_name, new.full_name);
  end if;

  if old.email is distinct from new.email then
    insert into public.profile_change_logs (user_id, changed_by, field_name, old_value, new_value)
    values (new.id, auth.uid(), 'email', old.email, new.email);
  end if;

  if old.avatar_url is distinct from new.avatar_url then
    insert into public.profile_change_logs (user_id, changed_by, field_name, old_value, new_value)
    values (new.id, auth.uid(), 'avatar_url', old.avatar_url, new.avatar_url);
  end if;

  if old.phone_country_code is distinct from new.phone_country_code then
    insert into public.profile_change_logs (user_id, changed_by, field_name, old_value, new_value)
    values (new.id, auth.uid(), 'phone_country_code', old.phone_country_code, new.phone_country_code);
  end if;

  if old.phone_number is distinct from new.phone_number then
    insert into public.profile_change_logs (user_id, changed_by, field_name, old_value, new_value)
    values (new.id, auth.uid(), 'phone_number', old.phone_number, new.phone_number);
  end if;

  if old.church_attendance_time is distinct from new.church_attendance_time then
    insert into public.profile_change_logs (user_id, changed_by, field_name, old_value, new_value)
    values (new.id, auth.uid(), 'church_attendance_time', old.church_attendance_time, new.church_attendance_time);
  end if;

  if old.is_being_discipled is distinct from new.is_being_discipled then
    insert into public.profile_change_logs (user_id, changed_by, field_name, old_value, new_value)
    values (new.id, auth.uid(), 'is_being_discipled', old.is_being_discipled::text, new.is_being_discipled::text);
  end if;

  return new;
end;
$$;

drop trigger if exists on_profile_updated_log_changes on public.profiles;

create trigger on_profile_updated_log_changes
after update of full_name, email, avatar_url, phone_country_code, phone_number, church_attendance_time, is_being_discipled on public.profiles
for each row execute function public.log_profile_changes();
