create table if not exists public.weekly_songs_header (
  id bigint generated by default as identity primary key,
  menu_title text,
  screen_title text,
  week_label text,
  subtitle text,
  is_active boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.weekly_songs (
  id bigint generated by default as identity primary key,
  title text not null,
  artist text,
  musical_key text,
  notes text,
  reference_url text,
  sort_order int default 0,
  is_active boolean default true,
  created_at timestamptz default now()
);

alter table public.weekly_songs_header enable row level security;
alter table public.weekly_songs enable row level security;

drop policy if exists "weekly_songs_header_read_active" on public.weekly_songs_header;
create policy "weekly_songs_header_read_active"
on public.weekly_songs_header for select
to authenticated
using (is_active = true);

drop policy if exists "weekly_songs_read_active" on public.weekly_songs;
create policy "weekly_songs_read_active"
on public.weekly_songs for select
to authenticated
using (is_active = true);

drop policy if exists "weekly_songs_header_admin_all" on public.weekly_songs_header;
create policy "weekly_songs_header_admin_all"
on public.weekly_songs_header for all
to authenticated
using (public.current_user_is_super_admin())
with check (public.current_user_is_super_admin());

drop policy if exists "weekly_songs_admin_all" on public.weekly_songs;
create policy "weekly_songs_admin_all"
on public.weekly_songs for all
to authenticated
using (public.current_user_is_super_admin())
with check (public.current_user_is_super_admin());

insert into public.weekly_songs_header (
  menu_title,
  screen_title,
  week_label,
  subtitle,
  is_active
)
select
  'Canciones semanales',
  'Repertorio de la semana',
  'Esta semana',
  'Repertorio preparado por el equipo de alabanza.',
  true
where not exists (select 1 from public.weekly_songs_header);

update public.weekly_songs_header
set screen_title = 'Repertorio de la semana'
where trim(coalesce(screen_title, '')) = trim(coalesce(menu_title, ''));
